### PR TITLE
refactor: Changed the parameter from "rut" to "id" for updating a user

### PR DESCRIPTION
**Pull request by GnesisVSS**

### CODE REVIEW

**Comment by spancavil** [comment]
Hello Gene!
As I mentioned to Teresa: the change is fine, but next time I'll ask you for the following format <Endpoint => the change>, like this
PATCH /update?id=<user_ud> => Change "rut" to "id" in params

Also I have a question: The logged in user should be able to change their information, but I see that this is not possible. Could you please check this? Thanks.

**Comment by GnesisVSS** [comment]
Hello Sebas! I've updated the commit message format and added a new endpoint to allow users to update their own information. Thanks!

**Comment by spancavil** [comment]
Nice Tere! Yes I'm agree that it could be another endpoint for the user to update their info.

I tried it and I got this error:
image
I don't know if some data or .env variables are missing. Could you check it? Thank you!

**Comment by GnesisVSS** [comment]
Hello sebas! requested changes made

**Review by spancavil — APPROVED** [review]
Well done!

**Pull request merged**
